receiver_id: '999999999'
hbx_id: 'dc0'
environment: 'test'
invalid_argument_queue: 'dc0.errors.invalid_arguements'
processing_failure_queue: 'dc0.errors.processing_failures'
request_exchange: "dc0.test.e.direct.requests"
event_exchange: "dc0.test.e.topic.events"
event_publish_exchange: "dc0.test.e.fanout.events"
amqp_uri: "amqp://guest:guest@localhost:5672"
file_storage_uri: "http://test.com:8083/files/"
