production:
  sessions:
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: <%= ENV['EDIDB_DB_NAME'] || 'edidb_prod' %>
      <% if ENV['EDIDB_DB_AUTH'] %>
      username: <%= ENV['EDIDB_DB_USERNAME'] %>
      password: <%= ENV['EDIDB_DB_PASSWORD'] %>
      <% end %>

      hosts:
        - <%= ENV['EDIDB_DB_HOST'] || 'localhost' %>:<%= ENV['EDIDB_DB_PORT'] || '27017' %>
      options:
        <% if ENV['EDIDB_DB_AUTH'] %>
        replica_set: <%= ENV['EDIDB_DB_REPLICA_SET_NAME'] %>
        <% end %> 

        write:
          w: 1
          j: true

        skip_version_check: true

development:
  sessions:
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: <%= ENV['EDIDB_DB_NAME'] %>_dev
      <% if ENV['EDIDB_DB_AUTH'] %>
      username: <%= ENV['EDIDB_DB_USERNAME'] %>
      password: <%= ENV['EDIDB_DB_PASSWORD'] %>
      <% end %>

      hosts:
        - <%= ENV['EDIDB_DB_HOST'] || 'localhost' %>:<%= ENV['EDIDB_DB_PORT'] || '27017' %>
      options:
        <% if ENV['EDIDB_DB_AUTH'] %>
        replica_set: <%= ENV['EDIDB_DB_REPLICA_SET_NAME'] %>
        <% end %>

        skip_version_check: true


test:
  sessions:
    default:
      database: gluedb_test<%= ENV['TEST_ENV_NUMBER'] %>
      hosts:
        - localhost:27017
      options:
        j: true
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
