site:
  short_name: "Access Health CT"
  long_name: "Access Health CT DB"
  copyright_period_start: "2017"

  social_media:
    facebook_url: ""

contact_center:
  name: "Access Health Connecticut"
  address: "133 Portland Street"
  city: "Hartford"
  state_abbreviation: "CT"
  postal_code: "02114"

abbrev: "mhc"

aca:
  enrollment_policy_report_name: "CCA_PRODUCTION_ENROLLMENT"
