name: Build reports image

on:
  push: #temp to register workflow
  workflow_dispatch:
    inputs:
      branch:
        default: 'master'
        description: 'Branch to build'
        required: true
      commit_sha:
        description: 'Commit sha to build'
        required: true
  repository_dispatch:
    types:
      - build-reports-image

concurrency:
  group: reports-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      client: ${{ steps.prep.outputs.client }}
      branch: ${{ steps.prep.outputs.branch}}
      commit_sha: ${{ steps.prep.outputs.commit_sha }}
    steps:
      - name: Set variables from workflow dispatch
        id: prep
        run: |
          if [[ "${{github.event_name}}" == "repository_dispatch" ]]; then 
            echo ::set-output name=client::${{ github.event.client_payload.client }}
            echo ::set-output name=branch::${{ github.event.client_payload.branch }}
            echo ::set-output name=commit_sha::${{ github.event.client_payload.commit_sha }}
          else
            echo ::set-output name=client::${{ github.event.inputs.client }}
            echo ::set-output name=branch::${{ github.event.inputs.branch }}
            echo ::set-output name=commit_sha::${{ github.event.inputs.commit_sha }}       
          fi 

  build-and-upload-image:
    runs-on: ubuntu-latest
    needs: [prep]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.prep.outputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          # Key is named differently to avoid collision
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build reports Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          file: .docker/production/Dockerfile.gha
          target: reports
          tags: ghcr.io/health-connector/gluedb:cca-reports
          build-args: |
            COMMIT_SHA=${{ needs.prep.outputs.commit_sha }}
            BRANCH=${{ needs.prep.outputs.branch }}
